"""LangGraph node for image requirement analysis (Agent 4).

Analyzes the generated article content to determine where images are needed,
what type (cover / section / inline), keywords for search, and placeholder
IDs to be replaced later.
"""

import json
import logging
import re
from typing import List

from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI

from app.agent.state import ArticleGenState
from app.config import settings
from app.constants.prompt import PromptConstant
from app.schemas.article import ImageRequirement

logger = logging.getLogger(__name__)


def _extract_placeholders_from_content(content: str) -> List[dict]:
    """Parse ``[IMAGE:position=N,keywords=K,type=T]`` markers already present
    in the content generated by Agent 3.

    Returns a list of raw requirement dicts extracted from the content.
    """
    pattern = r"\[IMAGE:\s*position=(\d+)\s*,\s*keywords=([^,\]]+)\s*(?:,\s*type=(\w+))?\s*\]"
    requirements = []
    for match in re.finditer(pattern, content):
        requirements.append({
            "position": int(match.group(1)),
            "keywords": match.group(2).strip(),
            "type": match.group(3) if match.group(3) else "inline",
        })
    return requirements


def analyze_images_node(state: ArticleGenState) -> dict:
    """分析文章中的图片需求。

    Uses ChatOpenAI (non-streaming) to examine the article content and produce
    a structured list of image requirements.  If the content already contains
    ``[IMAGE:...]`` placeholders those are parsed directly; otherwise the LLM
    is asked to propose image positions.
    """
    content = state.get("content", "")
    selected_title = state.get("selected_title") or {}
    main_title = selected_title.get("main_title", "") if selected_title else ""

    if not content:
        logger.warning("No content to analyze for images")
        return {"image_requirements": []}

    # First pass — try to extract placeholders already inserted by Agent 3
    placeholders = _extract_placeholders_from_content(content)
    if placeholders:
        logger.info(
            "Found %d existing image placeholders in content", len(placeholders)
        )
        # Normalise into ImageRequirement objects
        image_requirements = []
        for i, ph in enumerate(placeholders, start=1):
            image_requirements.append(
                ImageRequirement(
                    position=ph["position"],
                    type=ph["type"],
                    section_title="",
                    image_source=state.get("image_source", "DASHSCOPE").upper(),
                    keywords=ph["keywords"],
                    prompt="",
                    placeholder_id=str(ph["position"]),
                )
            )
        return {"image_requirements": [r.model_dump() for r in image_requirements]}

    # Second pass — no placeholders, ask the LLM to analyse
    enabled_methods = state.get("enabled_image_methods") or ["DASHSCOPE", "local"]
    enabled_methods_text = ", ".join(enabled_methods)

    prompt = PromptConstant.AGENT4_IMAGE_REQUIREMENTS_PROMPT.format(
        main_title=main_title,
        content=content,
        enabled_methods_text=enabled_methods_text,
    )

    logger.info("Analyzing image requirements via LLM")

    llm = ChatOpenAI(
        api_key=settings.dashscope_api_key,
        base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",
        model=settings.dashscope_model,
        temperature=0.3,
    )

    response = llm.invoke([HumanMessage(content=prompt)])
    result_text = response.content

    if isinstance(result_text, list):
        text_parts = []
        for block in result_text:
            if isinstance(block, dict) and block.get("text"):
                text_parts.append(block["text"])
        result_text = "".join(text_parts)

    # Parse JSON
    result_data = json.loads(result_text)
    if isinstance(result_data, dict):
        result_data = result_data.get("image_requirements", result_data)
    if not isinstance(result_data, list):
        result_data = [result_data]

    image_requirements = [ImageRequirement(**item) for item in result_data]

    # Assign placeholder IDs if missing
    for i, req in enumerate(image_requirements):
        if not req.placeholder_id:
            req.placeholder_id = str(i + 1)

    logger.info("Generated %d image requirements", len(image_requirements))
    return {"image_requirements": [r.model_dump() for r in image_requirements]}
